field.field.*.*.*.third_party.entity_reference_validators:
  type: mapping
  label: 'Entity reference validator field settings'
  mapping:
    circular_reference:
      type: boolean
      label: 'Prevent circular references'
    circular_reference_deep:
      type: boolean
      label: 'Recursively check circular references'
    duplicate_reference:
      type: boolean
      label: 'Prevent multiple references to the same entity'
